server:
  port: 8001
spring:
  application:
    # 这个name就是注册进Eureka的名字
    name: cloud-payment-service
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///db2019?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 所有entity别名类所在的包
  type-aliases-package: com.huang.springcloud.entity

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册消息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版
      # defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

  instance:
    # 更改eureka下的主机名称
    instance-id: payment8001
    # 访问路径可以显示ip地址
    prefer-ip-address: true

